# Generated by Django 6.0 on 2025-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='123', max_length=7),
        ),
    ]
