# Generated by Django 6.0 on 2025-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
