# Generated by Django 6.0 on 2025-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
